### ISSUE TITLE
After install the app i get Redirections error

### ISSUE THREAD

**Issue by Maexwell-nolen** [ppfeufer/aa-discord-ping-formatter#7]
Hello Guys,

before i installed the app i was able to use the website without any problems. But when I wanted to install the app and followed the tutorial, I only got a redirect error when I called up the page. What did I do wrong?

**Comment by ppfeufer** [comment]
Did you run:
```python
python manage.py collectstatic
python manage.py migrate
```

and did your restart supervisor?

**Comment by Maexwell-nolen** [comment]
jep same error

the log files are clean

**Comment by ppfeufer** [comment]
You have any custom templates?
Which plugin version you are running?

**Comment by ppfeufer** [comment]
2 weeks with no answer, I am going to assume you figured it out somehow and close this one.

**Comment by 4tt1c** [comment]
Hey,
i face the same issue.
I installed the latest version of your plugin and updated to the latest AA version.
Collectstatic, migration and auth restart were made and it is installed following the instructions.

The only changes i've made are the custom templates for groups, fleet types, webhooks, fleet comms, locations and doctrines.

@Maexwell-nolen did you fix the problem? If yes, what is your solution?

**Comment by ppfeufer** [comment]
Check the logs pls, let me know if there is anything in them, related to that error.

**Comment by Maexwell-nolen** [comment]
i've install the new version and it works

**Comment by 4tt1c** [comment]
Since all of us ssem to be german, we should switch to german and i would translate the solution after we've fixed the problem ;-)

@Maexwell-nolen  Which new versions did you install? AA, or just the formatter?

@ppfeufer  The logs are not very useful. Nothing failure related in here. 
This morning i've updated alliance auth and python to the latest version but the error still appears.
I followed https://allianceauth.readthedocs.io/en/latest/installation/upgrade_python.html to update to the latest versions of everything.

Edit:
The redirection hops between 
/account/login/?next=/dashboard/
/dashboard/
/account/login/?next=/dashboard/
/dashboard/
...

**Comment by 4tt1c** [comment]
I fixed the problem with the following:

Update to the latest Python version following this guides:
https://allianceauth.readthedocs.io/en/latest/installation/upgrade_python.html

Update to the latest Alliance Auth version with this guide:
https://allianceauth.readthedocs.io/en/latest/installation/allianceauth.html#updating

After running 
`source ./activate`
`pip install --upgrade allianceauth`
`allianceauth update ./myauth`
`python ./manage.py migrate`
`python ./manage.py collectstatic`
`supervisorctl restart myauth:`
Alliance Auth operates as expected.
(Make sure to use absolute paths when using the command mentioned above)

Thank you for your great work and your really nice tool @ppfeufer
